#version: '3'
services:
  conwaygui:
    image: docker.io/natbodocker/conwayguilifelocal:1.1
##    image: conwayguilifelocal:1.0
    ports:
      - "7110:7110"
    environment:
#      - HOST_IP=130.136.113.239
#      - HOST_IP=192.168.1.9
      - HOST_IP=localhost
#    network_mode: "host"


## docker-compose -f conwaygui.yaml -p conwaygui up   
